In [1]:
my_list = [1,2,3]


In [3]:
import numpy as np

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[3,4,5],[6,7,8]]

In [9]:
# 2-D ARRAY
np.array(my_mat)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.20001147, 0.88876468, 0.48131627, 0.55740424, 0.19152292])

In [16]:
np.random.randint(1,100)

39

In [17]:
np.random.randint(1,100,20)

array([88, 68, 88, 27, 18, 19, 25, 49,  4, 83, 27, 80, 88, 95, 28, 31, 96,
       26,  7, 52])

In [18]:
arr=np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr.reshape(6,5)

ValueError: cannot reshape array of size 25 into shape (6,5)

In [22]:
arr.max()

24

In [29]:
x=45
arr[4]=45

In [30]:
arr

array([ 0,  1,  2,  3, 45,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr.max()

45

In [32]:
arr.argmax()

4

In [33]:
arr.dtype

dtype('int32')

In [34]:
from numpy.random import randint

In [38]:
randint(2,567656565)

534923575